### PR TITLE
Catch and log any mail exception to prevent crashing logstash

### PR DESCRIPTION
**Pull request by FredFool**
I noticed that if for instance the smtp host is down or cant be reached, the mail command fails and crashes the whole logstash instance. The process is stil active, but all modules and configuration get reinitialized, any input listeners go down to and take a while to come up again.

I fixed this in 1.4.2 for me and its working without probs ever since.

### CODE REVIEW

**Comment by purbon** [comment]
Hi @FredFool, thanks a lot for your contribution. In order to move forward with your contribution you will need to sign the CLA, more info at -> https://www.elastic.co/contributor-agreement

**Comment by purbon** [comment]
It would be also nice to have some test to check for regressions on this behaviour, thanks a lot for your contribution and time.

**Comment by purbon** [comment]
Closing this in benefit of #28 as it has the same fix and test to verify the regression.

**Comment by kurtymckurt** [comment]
I ran into this problem as well.  It'd be helpful if you also included  the exception message with it for further debugging.

**Comment by purbon** [comment]
@kurtymckurt thanks for your feedback, can you elaborate a bit more, are you using the last version of this plugin? are you proposing to enright the message output?

**Comment by kurtymckurt** [comment]
I'm not. I'm still utilizing 1.4.2, but found this to resolve my crashing issue.  I just thought it should have the exception when logging the warning.  I can see now that master does do that.  Thank.

**Pull request closed without merging**
