### PR TITLE
Remove match config

### PR DESCRIPTION
**Pull request by wiibaa**
PR for #11 
I did not reindent correctly the code because it affected strangely the diff view.

### CODE REVIEW

**Comment by suyograo** [comment]
@wiibaa thanks. Can you rebase?

**Comment by wiibaa** [comment]
@suyograo done! should I also bump the version to 2.0.0 in this PR as removing this settings break backward-compat ?

**Comment by purbon** [comment]
@suyograo should we get this in nowadays that we aim to introduce 2.0 release? I guess is a good point isn't?

**Comment by suyograo** [comment]
@purbon ok to merge this to master. We already have a v1 branch for backward incompatible changes..

**Comment by purbon** [comment]
This has been merged in https://github.com/logstash-plugins/logstash-output-email/commit/71bffbe6b7a9f9c582d75c4fb26fd0c8d27a3487, thanks a lot for your time and contribution @wiibaa !!

**Pull request closed without merging**
