### PR TITLE
support ssl

### PR DESCRIPTION
**Pull request by lishunan246**
Thanks for contributing to Logstash! If you haven't already signed our CLA, here's a handy link: https://www.elastic.co/contributor-agreement/

### CODE REVIEW

**Comment by jstoja** [comment]
@lishunan246 a comma is missing on the new `:ssl` line that you added. Can you fix it to solve tests?

**Comment by jstoja** [comment]
The tests will pass after #49. This will be mergeable right after I think.
cc @jordansissel

**Comment by colinsurprenant** [comment]
Is there a way to include test(s) for this new option?

**Comment by jstoja** [comment]
I looked at Rumbster (that is used as a SMTP server to mock mails) and it uses gserver that doesn't handle SSL.
So I don't think this can be added to tests easily (exactly like StartTLS and other features that aren't tested either).

**Comment by colinsurprenant** [comment]
@jstoja Right, ok.
 
If we are stuck at manually testing this for practical reasons, I'd like these to see these tests reports here in this PR.

**Comment by colinsurprenant** [comment]
#49 is merged - @lishunan246 can you rebase?

**Comment by colinsurprenant** [comment]
lishunan246 oups. I think you included the last commits form master - this is now conflicting and cannot be merge. Can you clean this branch history? Thanks.

**Comment by lishunan246** [comment]
It seems fine now. Anything else needs to be done?

**Comment by colinsurprenant** [comment]
@lishunan246 yes it is, thanks! 

I understand it might be difficult to add specific tests for this here but I'd really like to see manual tests done and reported here if possible?

**Comment by lishunan246** [comment]
https://github.com/mikel/mail/blob/master/spec/mail/network/delivery_methods/smtp_spec.rb
I am sure this option works with stmp, haven't tried other methods though.

**Comment by colinsurprenant** [comment]
@lishunan246 but did you test it yourself?

**Comment by lishunan246** [comment]
I test it with my QQMail.

**Comment by colinsurprenant** [comment]
@lishunan246 All right - I looked at the `mikel/mail` code and now I understand my confusion - in `mikel/mail` the `:ssl` and :`tls` options are actually the same, see https://github.com/mikel/mail/commit/8416cc81cd6a03f3bc9a863ee04cc5fdfec8bcc2 

Now, here we expose the `use_tls` option which really maps to  `:enable_starttls_auto` in `mikel/mail`.

This is really confusing and I think we should expose the `tls` option instead of `ssl` and we should deprecate and rename the `use_tls` in favor of `starttls`.

**Comment by jordansissel** [comment]
IIRC there are 3 communication handshake options for SMTP:
1) SMTP over TCP
2) SMTP after [STARTTLS ](https://tools.ietf.org/html/rfc3207)
3) SMTP using SSL/TLS handshake

So maybe instead of two options (starttls vs tls), we have a single option with 3 possible value? I'm not sure what to call this setting. "connect mode" maybe? There's an option right now [`via`](https://www.elastic.co/guide/en/logstash/current/plugins-outputs-email.html#plugins-outputs-email-via) which lets you choose SMTP or Sendmail, so maybe we could reuse this and add `smtp+tls` and `smtp+starttls` options?

My rational here is that it doesn't make sense to have both `tls` and `starttls` at the same time, so these settings are modal. Further, `starttls` when the `via` is `sendmail` also doesn't make sense.

Thoughts on using `via` and adding two values to it (one for STARTTLS, one for SNMP over TLS) ?

**Comment by jordansissel** [comment]
Ruby Net::SMTP also has two modes for starttls: enable_starttls and enable_starttls_auto. `auto` seems to fall back to plain text if starttls is unsupported: https://github.com/ruby/ruby/blob/trunk/lib/net/smtp.rb#L314-L319, https://github.com/ruby/ruby/blob/trunk/lib/net/smtp.rb#L555

the `mail` gem sets enable_starttls_auto by default.

**Comment by colinsurprenant** [comment]
Good point @jordansissel. So looking at the SMTP library, there are 3 modes:

- enable_starttls
> Enables SMTP/TLS (STARTTLS) for this object
- enable_starttls_auto
> Enables SMTP/TLS (STARTTLS) for this object if server accepts
- enable_tls
> Enables SMTP/TLS (SMTPS: SMTP over direct TLS connection)

The distinction between `enable_starttls` and `enable_starttls_auto` is that `enable_starttls_auto` will downgrade to plain text if the server does not support it. 

It seems the 3 are mutually exclusive so we could either have a `connect mode` as you suggested with `starttls`, `starttls_auto` and `tls` or have just a `via` with `sendmail`, `smtp`, `smtl_tls`, `smtp_starttls`, `smtp_starttls_auto` ?

**Comment by jordansissel** [comment]
> a via with sendmail, smtp, smtl_tls, smtp_starttls, smtp_starttls_auto ?

I think we can use 4 (omit the 'auto' and have that implied by `smtp`): sendmail, smtp, smtp_tls, smtp_starttls

Omitting the 'auto' option might be possible since we could make 'auto' be enabled when `smtp` is used.  The implication being that `smtp_starttls` is intended to fail if the server does not support starttls.

**Comment by colinsurprenant** [comment]
@jordansissel +1

**Comment by colinsurprenant** [comment]
@lishunan246 are you interested in proposing changes as discussed here? Could be here or in a new PR.

**Pull request closed without merging**
